aggiornata la sezione report
bitRocket-dev/rocket-cms pull request #325
Opened 2022-09-06 15:05 UTC by robertolaporta-bitrocketdev

## Descrizione

 Aggiunte nella sezione report:
-  ui minima
- logica redux( nuova action update report)
- creato nuovo selettore(non dinamico)

## Tipologia di cambiamento - selezionare il tipo di cambiamento pertinente:

- [ ] 🐛 Bug fix (cambiamento non critico che risolve un problema)
- [x] 🆕 New feature (cambiamento non critico che aggiunge funzionalità)
- [ ] 💄 Adjustment (regolazione visiva o semplici regolazioni logiche)
- [ ] 💥 Breaking change (correzione o funzionalità che potrebbero causare il mancato funzionamento di quelle esistenti come previsto)

## Testati su - selezionare il tipo di dispositivo pertinente:

- [ ] Chrome

2022-09-07 08:23 UTC, riccardogenova-bitrocketdev requested changes

2022-09-07 08:23 UTC, riccardogenova-bitrocketdev commented on src/@ducks/report/selectors.ts
> +export const selectorReportByMonth = (store: TStore, month: TMonth) => {
*selectorReportListByMonth

2022-09-07 08:23 UTC, riccardogenova-bitrocketdev commented on src/@ducks/report/selectors.ts
> +export const selectorReportByAssignment = (store: TStore, month: TMonth, idAssignment: TAssignment['id']) => {
selectorReportListByAssignment

2022-09-07 08:23 UTC, riccardogenova-bitrocketdev commented on src/components/ReportDetail.tsx
> +            // updateReport({ ...report, year: '',month});
?

2022-09-07 08:33 UTC, robertolaporta-bitrocketdev commented on src/components/ReportDetail.tsx
> +            // updateReport({ ...report, year: '',month});
è codice inutilizzato che rompeva l'app e basta

2022-09-07 08:34 UTC, riccardogenova-bitrocketdev commented on src/components/ReportDetail.tsx
> +            // updateReport({ ...report, year: '',month});
Allora eliminiamo, non lasciamo codice commentato che non serve

2022-09-08 09:19 UTC, riccardogenova-bitrocketdev approved these changes

2022-09-08 09:20 UTC, merged