Rinominato developer in user
bitRocket-dev/rocket-cms pull request #442
Opened 2022-09-23 17:00 UTC by robertolaporta-bitrocketdev

## Descrizione

Cambiati alcuni selettori developer in user 

## Tipologia di cambiamento - selezionare il tipo di cambiamento pertinente:

- [ ] 🐛 Bug fix (cambiamento non critico che risolve un problema)
- [ ] 🆕 New feature (cambiamento non critico che aggiunge funzionalità)
- [x] 💄 Adjustment (regolazione visiva o semplici regolazioni logiche)
- [ ] 💥 Breaking change (correzione o funzionalità che potrebbero causare il mancato funzionamento di quelle esistenti come previsto)

## Testati su - selezionare il tipo di dispositivo pertinente:

- [x] Chrome
- [ ] Firefox
- [ ] Brave

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev requested changes

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/@ducks/company/constants.ts
> +  | 'CompanyDetail/users'
Users

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/@ducks/device/selectors.ts
> +export const selectorNumberDevicesForuser = (store: TStore, idUser: TUser['id']) => {
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/@ducks/remoteWorking/constants.ts
> +export type TPageRemoteWorkingDetail = 'RemoteWorkingForuser/Create';
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/@ducks/timing/constants.ts
> +export type TPageTimingDetail = 'Timing/Create' | 'TimingForuser/Create';
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/@ducks/user/constants.ts
> +  | 'user/Create';
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components-form/Company/index.tsx
> +  const [userId, setUserId] = useState(idUserParam || '');
isUser setIdUser

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components-form/User/index.tsx
> +      const newuser = {
newUser

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components/UserList/Allocated.tsx
> +        {developerList.map(user => (
userList (cambiamo il nome sulla variabile estratta dal selettore)

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components/UserList/Expired.tsx
> +        {developerList.map(user => (
vedi commento precedente

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components/UserList/Inactive.tsx
> +        {developerList.map(user => (
vedi commento precedente

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components/UserList/Internship.tsx
> +  const developerList = useAppSelector(selectorUserInternshipList);
vedi commento precedente

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/components/UserSelect.tsx
> +    const userList = useAppSelector(selectorDeveloperList);
Se utilizzi il selettore DeveloperList allora ha senso mantenere il nome del componente come DeveloperSelect

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/constants/config.ts
> +      body: 'Ecco qui i user disponibili per la posizione:%0D%0D',
rimane i developer

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/hooks/usePageURL.ts
> +      case 'user/Create':
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/hooks/usePageURL.ts
> +      case 'TimingForuser/Create':
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/hooks/usePageURL.ts
> +      case 'RemoteWorkingForuser/Create':
User

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/hooks/usePageURL.ts
> +      case 'CompanyDetail/users':
Users

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/hooks/usePageURL.ts
> +      // #region :::  user LIST
USER

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/hooks/usePageURL.ts
> +      // #region :::  user DETAIL
USER

2022-09-25 21:12 UTC, riccardogenova-bitrocketdev commented on src/pages/PageDeviceCreate/index.tsx
> +  const isuserNotValid = !!idUser && !userName;
isUser

2022-09-26 08:36 UTC, robertolaporta-bitrocketdev commented on src/components/UserList/Allocated.tsx
> +        {developerList.map(user => (
Gli allocati sono solo i developer. Dobbiamo comunque considerarli User e basta?

2022-09-26 11:54 UTC, merged